name: olive
description: Olive is a set of extension methods to make the cross-platform easier, cleaner, and more expressive.
version: 0.0.6
homepage: https://github.com/m-sadegh-sh/olive

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  lint: ^1.8.2
  test: ^1.21.1
